'use client';

import {useEffect,useState} from 'react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
import works from './works.json';

const selections=[
  {id:'children',label:'बाल साहित्य',en:'For the curious reader',title:'चित्र, कथा आ कल्पना।',text:'प्रीति ठाकुरक चित्रकथा आ अनुवादसँ बाल साहित्यक संसारमे प्रवेश करू।',ids:['p0','p1','p13']},
  {id:'literature',label:'कथा आ पद्य',en:'For the literary explorer',title:'लघु कथासँ उपन्यास धरि।',text:'गजेन्द्र ठाकुरक कथात्मक आ काव्यात्मक लेखनक तीन प्रवेश-द्वार।',ids:['g0','g2','g4']},
  {id:'memory',label:'अभिलेख आ शोध',en:'For the archive explorer',title:'स्मृतिक पन्ना खोलू।',text:'पञ्जी-अभिलेख, साहित्यक इतिहास आ दूनू रचनाकारक समालोचना पढ़ू।',ids:['p16','g6','j0']}
];

export function ReadingPaths(){return <Tabs defaultValue="children" className="reading-paths"><TabsList aria-label="पढ़बाक बाट चुनू" className="path-tabs">{selections.map(s=><TabsTrigger key={s.id} value={s.id}>{s.label}</TabsTrigger>)}</TabsList>{selections.map(s=><TabsContent key={s.id} value={s.id} className="path-panel"><div><p className="eyebrow" lang="en">{s.en}</p><h3>{s.title}</h3><p>{s.text}</p></div><ol>{s.ids.map((id,i)=>{const w=works.find(w=>w.id===id)!;return <li key={id}><span>0{i+1}</span><a href={w.url}>{w.title}<small>{w.name} <b aria-hidden="true">↗</b></small></a></li>})}</ol></TabsContent>)}</Tabs>}

export function Catalogue(){const[query,setQuery]=useState('');const[author,setAuthor]=useState('all');const[expanded,setExpanded]=useState(false);
const normalized=query.normalize('NFC').toLocaleLowerCase().replace(/[०-९]/g,d=>String('०१२३४५६७८९'.indexOf(d))).trim();
const filtered=works.filter(w=>(author==='all'||w.author===author)&&[w.title,w.name,w.kind,w.year,w.keywords,w.note].join(' ').normalize('NFC').toLocaleLowerCase().includes(normalized));
const visible=expanded?filtered:filtered.slice(0,6);
return <div className="catalogue"><div className="catalogue-tools"><label htmlFor="work-search">पोथी ताकू <span lang="en">/ Search the selection</span><Input id="work-search" type="search" value={query} onChange={e=>{setQuery(e.target.value);setExpanded(false)}} placeholder="शीर्षक, लेखक, वर्ष…"/></label><div className="author-filters" role="group" aria-label="रचनाकार चुनू">{[['all','सभ'],['preeti','प्रीति'],['gajendra','गजेन्द्र'],['joint','साझा']].map(([value,label])=><Button key={value} variant="ghost" aria-pressed={author===value} onClick={()=>{setAuthor(value);setExpanded(false)}}>{label}</Button>)}</div></div><div className="results-line"><span role="status" aria-live="polite">{filtered.length} रचना · {visible.length} देखाओल</span><span lang="en">SELECTED WORKS / {works.length}</span></div><div className="work-grid">{visible.map((w)=><article className={'work-card '+w.author} key={w.id}><div className="work-top"><span>{w.kind}</span><span>{w.year||'—'}</span></div><div><p className="work-author">{w.name}</p><h3><a href={w.url}>{w.title}<span className="work-arrow" aria-hidden="true">↗</span></a></h3></div><div className="work-bottom"><p>{w.note||'विदेह पुस्तक सूची'}</p><a href={w.source} aria-label={w.title+' — स्रोत'}>स्रोत ↗</a></div></article>)}</div>{filtered.length===0&&<div className="no-results"><h3>कोनो रचना नहि भेटल।</h3><p>दोसर शीर्षक वा लेखकक नामसँ ताकू।</p><Button onClick={()=>{setQuery('');setAuthor('all')}}>खोज मेटाउ</Button></div>}{filtered.length>6&&<Button className="show-more" variant="outline" onClick={()=>setExpanded(!expanded)}>{expanded?'कम देखाउ ↑':`बाकी ${filtered.length-6} रचना देखाउ ↓`}</Button>}<p className="catalogue-note">ई चुनल रचनाक सूची अछि। पूर्ण सूची लेल <a href="https://www.videha.co.in/pothi.htm">विदेह पोथी ↗</a> देखू। वर्ष संस्करणक अछि; “—” माने एहि सूचीमे वर्ष नहि देल गेल अछि।</p><noscript><p>पूरा कृति-सूची <a href="https://www.videha.co.in/pothi.htm">विदेह पोथी</a> पर पढ़ू।</p></noscript></div>}

export function ReadingProgress(){const[progress,setProgress]=useState(0);useEffect(()=>{let pending=false;const update=()=>{const max=document.documentElement.scrollHeight-window.innerHeight;setProgress(max>0?Math.min(100,window.scrollY/max*100):0);pending=false};const onScroll=()=>{if(!pending){pending=true;requestAnimationFrame(update)}};update();window.addEventListener('scroll',onScroll,{passive:true});window.addEventListener('resize',onScroll);return()=>{window.removeEventListener('scroll',onScroll);window.removeEventListener('resize',onScroll)}},[]);return <div className="reading-progress" aria-hidden="true" style={{transform:`scaleX(${progress/100})`}}/>}
