'use client';

import {useEffect,useState} from 'react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import works from './works.json';
import CatalogueView from './catalogue-view';

type ReadingPath={id:string;label:string;en:string;title:string;text:string;ids:string[];href?:string;linkTitle?:string;linkMeta?:string};
const selections:ReadingPath[]=[
  {id:'six-books',label:"छह नव पोथी",en:'GAJENDRA THAKUR · SIX BOOKS',title:"कविता, कथा आ किशोर साहित्य।",text:"छह स्रोत-संस्करणक परिचय; नव पाँखिक सभ 20 कथा आ कूट नामक सभ 13 अध्यायक द्विभाषिक चर्चा पढ़ू।",ids:[],href:'/gajendra-preeti/six-books/',linkTitle:'छह पोथी',linkMeta:'6 पोथी · मैथिली + English'},

  {id:'children',label:'बाल साहित्य',en:'For the curious reader',title:'चित्र, कथा आ कल्पना।',text:'प्रीति ठाकुरक चित्रकथा आ अनुवादसँ बाल साहित्यक संसारमे प्रवेश करू।',ids:['p0','p1','p13']},
  {id:'literature',label:'कथा आ पद्य',en:'For the literary explorer',title:'लघु कथासँ उपन्यास धरि।',text:'गजेन्द्र ठाकुरक कथात्मक आ काव्यात्मक लेखनक तीन प्रवेश-द्वार।',ids:['g0','g2','g4']},
  {id:'dreams',label:'स्वप्न मे मिज्झर होइत',en:'WHEN DREAMS MERGE · BILINGUAL BOOK GUIDE',title:'स्वप्नसँ भाषा, दर्शन आ न्याय धरि।',text:'उपयोगकर्ताद्वारा देल 2026 संशोधित मैथिली मूल संस्करणक 447 विषय-सूची प्रविष्टिक स्रोत-आधारित सारांश, 11 विस्तृत पठन आ English समकक्ष।',ids:[],href:'/gajendra-preeti/when-dreams-merge/',linkTitle:'स्वप्न मे मिज्झर होइत · WHEN DREAMS MERGE',linkMeta:'447 सार-रेकर्ड · 11 विस्तृत पठन · मैथिली + English'},
  {id:'water',label:'गोहि सभक बीच जलसमाधि',en:'WATER-BURIAL AMONG THE CROCODILES · BILINGUAL BOOK GUIDE',title:'नाम, जल, स्मृति आ न्याय केर 301-अध्याय यात्रा।',text:'उपयोगकर्ताद्वारा देल मैथिली त्रयीसँ अध्याय -100 सँ 200 धरि सभ 301 अध्यायक स्रोत-आधारित सार, 19 कथा-चक्र, विषय-पथ आ English समकक्ष।',ids:[],href:'/gajendra-preeti/water-burial-among-the-crocodiles/',linkTitle:'गोहि सभक बीच जलसमाधि · WATER-BURIAL AMONG THE CROCODILES',linkMeta:'301 अध्याय · 3 भाग · 19 कथा-चक्र · मैथिली + English'},
  {id:'parallel',label:'समानान्तर दर्शन',en:'PARALLEL PHILOSOPHY · BILINGUAL GUIDE',title:'172 अध्यायक मैथिली–अंग्रेजी दार्शनिक यात्रा।',text:'खण्ड 1 केर 72 आ खण्ड 2 केर 100 अध्याय—सभक स्रोत-आधारित द्विभाषी सार आ अध्याय-पथ।',ids:[],href:'/gajendra-preeti/parallel-philosophy/',linkTitle:'गजेन्द्र ठाकुरक समानान्तर दर्शन · PARALLEL PHILOSOPHY',linkMeta:'172 अध्याय · 2 खण्ड · 23 विषय-खण्ड · मैथिली + English'},
  {id:'history',label:'समानान्तर इतिहास',en:'PARALLEL HISTORY · BILINGUAL GUIDE',title:'178 अध्यायक मिथिला–वज्जि–अंग इतिहास यात्रा।',text:'सामान्य-राजनीतिक इतिहासक 28 आ सामाजिक-सांस्कृतिक-आर्थिक इतिहासक 150 अध्याय—सभक स्रोत-आधारित मैथिली–अंग्रेजी सार आ अध्याय-रूपरेखा।',ids:[],href:'/gajendra-preeti/parallel-history/',linkTitle:'मिथिला, वज्जि आ अंगक समानान्तर इतिहास · PARALLEL HISTORY',linkMeta:'178 अध्याय · 2 पोथी · 20 स्रोत-खण्ड · मैथिली + English'},
  {id:'classical',label:'शास्त्रीय दर्शन',en:'CLASSICAL PHILOSOPHY · BILINGUAL RESEARCH READER',title:'चारि मूल दर्शन-ग्रन्थक 32 स्रोत-आधारित अध्ययन इकाइ।',text:'आत्मतत्त्वविवेक, भामती, न्यायकुसुमाञ्जलि आ तत्त्वचिन्तामणि—गजेन्द्र ठाकुरक मैथिली अनुवाद-परियोजनाक संग आठ विस्तृत अनुवाद-अनुलग्नक।',ids:[],href:'/gajendra-preeti/classical-philosophy/',linkTitle:'शास्त्रीय दर्शन · CLASSICAL PHILOSOPHY',linkMeta:'32 इकाइ · 4 ग्रन्थ · 8 अनुवाद-अनुलग्नक · मैथिली + English'},
  {id:'drama',label:'नाटक आ संस्कृत साहित्य',en:'DRAMA & SANSKRIT CLASSICS · BILINGUAL RESEARCH READER',title:'२२ कृतिक स्रोत-आधारित द्विभाषी नाट्य-साहित्य यात्रा।',text:'तेरह संस्कृत साहित्य-कृति आ रंग-संगमक नओटा मैथिली नाटक—English समकक्ष, विस्तृत अध्ययन आ स्रोतमे देल अंक, दृश्य, भाग, प्रवेशक तथा निरन्तर पाठ-संरचना सहित।',ids:[],href:'/gajendra-preeti/drama-classics/',linkTitle:'नाटक आ संस्कृत साहित्य · DRAMA & SANSKRIT CLASSICS',linkMeta:'22 कृति · 13 संस्कृत कृति · 9 रंग-संगम नाटक · मैथिली + English'},
  {id:'media',label:'मीडिया आ अध्ययन',en:'VIDEHA MEDIA & LEARNING',title:'डॉक्यूमेन्टरी, शिक्षण, काव्य आ सुगम्यता।',text:'समानान्तर इतिहास-दर्शन, शास्त्रीय दर्शन, नाटक, जलसमाधि शिक्षण-संसाधन, गीत-गजल, eLearning आ Accessible Videha सहित 28 स्रोत-दत्त लिंक एक ठाम।',ids:[],href:'/gajendra-preeti/media-learning/',linkTitle:'विदेह मीडिया आ अध्ययन',linkMeta:'28 लिंक · 4 सुव्यवस्थित पथ · मैथिली + English'},
  {id:'memory',label:'अभिलेख आ शोध',en:'For the archive explorer',title:'स्मृतिक पन्ना खोलू।',text:'पञ्जी-अभिलेख, साहित्यक इतिहास आ दूनू रचनाकार पर समालोचना पढ़ू।',ids:['p16','g6','j0']}
];

export function ReadingPaths(){return <Tabs defaultValue="children" className="reading-paths"><TabsList aria-label="पढ़बाक बाट चुनू" className="path-tabs">{selections.map(s=><TabsTrigger key={s.id} value={s.id}>{s.label}</TabsTrigger>)}</TabsList>{selections.map(s=><TabsContent key={s.id} value={s.id} className="path-panel"><div><p className="eyebrow" lang="en">{s.en}</p><h3>{s.title}</h3><p>{s.text}</p></div><ol>{s.href?<li><span>01</span><a href={s.href}>{s.linkTitle}<small>{s.linkMeta} <b aria-hidden="true">→</b></small></a></li>:s.ids.map((id,i)=>{const w=works.find(w=>w.id===id)!;return <li key={id}><span>0{i+1}</span><a href={w.url}>{w.title}<small>{w.name} <b aria-hidden="true">↗</b></small></a></li>})}</ol></TabsContent>)}</Tabs>}

export function Catalogue(){return <CatalogueView/>;}

export function ReadingProgress(){const[progress,setProgress]=useState(0);useEffect(()=>{let pending=false;const update=()=>{const max=document.documentElement.scrollHeight-window.innerHeight;setProgress(max>0?Math.min(100,window.scrollY/max*100):0);pending=false};const onScroll=()=>{if(!pending){pending=true;requestAnimationFrame(update)}};update();window.addEventListener('scroll',onScroll,{passive:true});window.addEventListener('resize',onScroll);return()=>{window.removeEventListener('scroll',onScroll);window.removeEventListener('resize',onScroll)}},[]);return <div className="reading-progress" aria-hidden="true" style={{transform:`scaleX(${progress/100})`}}/>}
