'use client';
import {useEffect,useState} from 'react';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import works from './works.json';
import readings from '../public/criticism/manifest.json';
import reviewLinks from './review-links.json';
const reviews=reviewLinks as Record<string,string>;
const categories=[...new Set(works.map(w=>w.kindEn))];
const years=[...new Set(works.map(w=>w.year).filter(y=>y!==null))].sort((a,b)=>Number(a)-Number(b));
const normalize=(value:string)=>value.normalize('NFC').toLowerCase().replace(/[०-९]/g,d=>String('०१२३४५६७८९'.indexOf(d))).trim();
function destination(url:string){const host=new URL(url).hostname;return host.includes('drive.google')?'Google Drive':host.includes('archive.org')?'Archive.org · PDF':host.includes('store.pothi')?'Pothi · Print / purchase':host.includes('play.google')?'Google Play Books':host.includes('github.io')?'Videha · Digital edition':'External publication';}
export default function CatalogueView({english=false}:{english?:boolean}){
 const[query,setQuery]=useState(''),[author,setAuthor]=useState('all'),[genre,setGenre]=useState('all'),[year,setYear]=useState('all');
 const clear=()=>{setQuery('');setAuthor('all');setGenre('all');setYear('all');};
 useEffect(()=>{const reveal=()=>{if(location.hash.startsWith('#work-')){clear();setTimeout(()=>document.getElementById(decodeURIComponent(location.hash.slice(1)))?.scrollIntoView({block:'start'}),100);}};reveal();addEventListener('hashchange',reveal);return()=>removeEventListener('hashchange',reveal);},[]);
 const filtered=works.filter(w=>(author==='all'||w.author===author)&&(genre==='all'||w.kindEn===genre)&&(year==='all'||String(w.year)===year)&&normalize([w.title,w.name,w.titleEn,w.nameEn,w.kind,w.kindEn,w.year,w.keywords,w.note,w.noteEn].join(' ')).includes(normalize(query)));
 return <div className="catalogue"><p className="catalogue-note">{english?`${works.length} selected works; the companion Reading Room covers ${readings.length} catalogue entries, including collected editions and digital resources. These are different units, not a complete count of published books.`:`${works.length} चुनल रचना; समालोचना-कक्षमे ${readings.length} सूची-प्रविष्टि अछि, जाहिमे संकलित संस्करण आ डिजिटल संसाधनो अछि। ई अलग-अलग गणना अछि, प्रकाशित पोथीक पूर्ण संख्या नहि।`} <a href="/gajendra-preeti/criticism/" lang={english?'en':'mai'}>{english?'English criticism →':'इंग्लिश समालोचना →'}</a></p><p id="search-guidance" className="search-guidance">{english?'Search Maithili titles, English names, or years in either numeral system (2009 / २००९).':'मैथिली शीर्षक, अंग्रेजी नाम वा दूनू अंक-पद्धतिमे वर्ष (2009 / २००९) सँ खोजू।'}</p><div className="catalogue-tools"><label htmlFor="work-search">{english?'Find a book':'पोथी ताकू'}<Input id="work-search" aria-describedby="search-guidance" type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder={english?'Title, author, year…':'शीर्षक, लेखक, वर्ष…'}/></label><div className="author-filters" role="group" aria-label={english?'Filter by writer':'रचनाकार चुनू'}>{[['all',english?'All':'सभ'],['preeti',english?'Preeti':'प्रीति'],['gajendra',english?'Gajendra':'गजेन्द्र'],['joint',english?'About both':'दुनूपर']].map(([value,label])=><Button key={value} variant="ghost" aria-pressed={author===value} onClick={()=>setAuthor(value)}>{label}</Button>)}</div></div>
 <div className="catalogue-refine"><label>{english?'Genre / role':'विधा / भूमिका'}<NativeSelect value={genre} onChange={e=>setGenre(e.target.value)}><NativeSelectOption value="all">{english?'All genres':'सभ विधा'}</NativeSelectOption>{categories.map(kind=><NativeSelectOption key={kind} value={kind}>{english?kind:works.find(w=>w.kindEn===kind)!.kind}</NativeSelectOption>)}</NativeSelect></label><label>{english?'Edition year':'संस्करण-वर्ष'}<NativeSelect value={year} onChange={e=>setYear(e.target.value)}><NativeSelectOption value="all">{english?'All years':'सभ वर्ष'}</NativeSelectOption>{years.map(y=><NativeSelectOption key={y} value={String(y)}>{y}</NativeSelectOption>)}<NativeSelectOption value="null">{english?'Year not recorded':'वर्ष नहि दर्ज'}</NativeSelectOption></NativeSelect></label><Button variant="outline" onClick={clear}>{english?'Reset filters':'फिल्टर हटाउ'}</Button></div>
 <div className="results-line"><span role="status" aria-live="polite">{filtered.length} / {works.length} {english?'works shown':'रचना देखाओल'}</span><span>{english?'All works visible by default':'सभ रचना आरम्भेसँ उपलब्ध'}</span></div><div className="work-grid">{filtered.map(w=>{const review=reviews[w.id];const extras=(w as typeof w&{alternates?:{label:string;url:string}[]}).alternates||[];return <article id={'work-'+w.id} data-citation-title={english?w.titleEn:w.title} className={'work-card '+w.author} key={w.id}><div className="work-top"><span>{english?w.kindEn:w.kind}</span><span>{w.year||'—'}</span></div><div><p className="work-author">{english?w.nameEn:w.name}</p><h3><a href={w.url}>{english?w.titleEn:w.title}<span className="work-arrow" aria-hidden="true">↗</span></a></h3><p className="destination-note" lang="en">{destination(w.url)} ↗</p></div><div className="work-bottom"><p>{english?w.noteEn:w.note||'विदेह पुस्तक सूची'}</p><a href={w.source}>{english?'Source':'स्रोत'} ↗</a></div><div className="work-reference-links"><a href={'#work-'+w.id} aria-label={(english?'Link to ':'कड़ी: ')+(english?w.titleEn:w.title)}>#{w.id.toUpperCase()}</a>{review&&<a href={'/gajendra-preeti/criticism/'+review+'.html'}>{english?'English criticism':'अंग्रेजी समालोचना'} →</a>}{extras.map(a=><a href={a.url} key={a.url}>{a.label} ↗</a>)}</div><small className="verified-note">{english?'Catalogue checked: 8 September 2026':'सूची-जाँच: 8 सितम्बर 2026'}</small></article>;})}</div>
 {!filtered.length&&<div className="no-results"><h3>{english?'No matching works.':'कोनो रचना नहि भेटल।'}</h3><Button onClick={clear}>{english?'Clear all filters':'सभ फिल्टर हटाउ'}</Button></div>}<p className="catalogue-note">{english?'This is a selected bibliography. Years describe editions, not necessarily first publication; all displayed years use 0–9. Search accepts both numeral systems. English title glosses do not imply an English edition exists.':'ई चुनल कृति-सूची अछि। वर्ष संस्करणक अछि, आवश्यक नहि जे प्रथम प्रकाशनक हो। देखाओल वर्षमे 0–9 अंकक प्रयोग अछि; खोजमे दूनू अंक-पद्धति चलैत अछि। अंग्रेजी शीर्षकक अर्थ ई नहि जे पोथीक अंग्रेजी संस्करण उपलब्ध अछि।'} <a href="https://www.videha.co.in/pothi.htm">{english?'Full Videha catalogue':'पूर्ण विदेह पोथी-सूची'} ↗</a></p></div>;
}
