'use client';

import {useEffect,useState} from 'react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import works from './works.json';
import CatalogueView from './catalogue-view';

type ReadingPath={id:string;label:string;en:string;title:string;text:string;ids:string[];href?:string;linkTitle?:string;linkMeta?:string};
const selections:ReadingPath[]=[
  {id:'children',label:'Children’s books',en:'For the curious reader',title:'Pictures, stories, imagination.',text:'Enter children’s literature through Preeti Thakur’s picture stories and translations.',ids:['p0','p1','p13']},
  {id:'literature',label:'Fiction and poetry',en:'For the literary explorer',title:'From short fiction to the novel.',text:'Three starting points in Gajendra Thakur’s fiction and poetry.',ids:['g0','g2','g4']},
  {id:'dreams',label:'When Dreams Merge',en:'COMPLETE BILINGUAL BOOK GUIDE',title:'From dream to language, philosophy and justice.',text:'Explore all 447 source-grounded records, 11 extended readings and the paired Maithili guide for the complete revised volume.',ids:[],href:'/gajendra-preeti/when-dreams-merge/en/',linkTitle:'WHEN DREAMS MERGE',linkMeta:'447 records · 11 extended readings · Maithili + English'},
  {id:'water',label:'Water-Burial Among the Crocodiles',en:'COMPLETE BILINGUAL NOVEL GUIDE',title:'Names, water, memory and justice across 301 chapters.',text:'Explore every chapter from -100 through 200, all 19 narrative arcs, thematic routes and the paired Maithili guide.',ids:[],href:'/gajendra-preeti/water-burial-among-the-crocodiles/en/',linkTitle:'WATER-BURIAL AMONG THE CROCODILES',linkMeta:'301 chapters · 3 principal parts · 19 narrative arcs · Maithili + English'},
  {id:'parallel',label:'Parallel Philosophy',en:'COMPLETE BILINGUAL GUIDE',title:'172 chapters across two volumes, in Maithili and English.',text:'Explore every chapter: 72 in Volume I and 100 in Volume II, with bilingual source-grounded summaries and chapter outlines.',ids:[],href:'/gajendra-preeti/parallel-philosophy/en/',linkTitle:'GAJENDRA THAKUR’S PARALLEL PHILOSOPHY',linkMeta:'172 chapters · 2 volumes · 23 thematic parts · Maithili + English'},
  {id:'history',label:'Parallel History',en:'COMPLETE BILINGUAL HISTORY GUIDE',title:'178 chapters across two complementary histories of Mithila, Vajji and Anga.',text:'Explore every chapter: 28 in General & Political History and 150 in Socio-Cultural-Economic History, with paired Maithili and English summaries and source chapter outlines.',ids:[],href:'/gajendra-preeti/parallel-history/en/',linkTitle:'PARALLEL HISTORY OF MITHILA, VAJJI & ANGA IN INDIA & NEPAL',linkMeta:'178 chapters · 2 books · 20 source sections · Maithili + English'},
  {id:'classical',label:'Classical Philosophy',en:'BILINGUAL RESEARCH READER',title:'32 source-grounded units across four foundational Sanskrit works.',text:'Explore Ātmatattvaviveka, Bhāmatī, Nyāyakusumāñjali and Tattvacintāmaṇi alongside eight detailed annexures from Gajendra Thakur’s Maithili translation programme.',ids:[],href:'/gajendra-preeti/classical-philosophy/en/',linkTitle:'CLASSICAL PHILOSOPHY · शास्त्रीय दर्शन',linkMeta:'32 units · 4 works · 8 translation annexures · Maithili + English'},
  {id:'drama',label:'Drama & Sanskrit Classics',en:'BILINGUAL RESEARCH READER',title:'Twenty-two source-grounded studies across two literary collections.',text:'Explore thirteen Sanskrit classics and all nine Rang-Sangam Maithili plays with their English counterparts, preserving the acts, scenes, parts, interludes and continuous-text structures supplied by the source editions.',ids:[],href:'/gajendra-preeti/drama-classics/en/',linkTitle:'DRAMA & SANSKRIT CLASSICS · नाटक आ संस्कृत साहित्य',linkMeta:'22 works · 13 Sanskrit classics · 9 Rang-Sangam plays · Maithili + English'},
  {id:'media',label:'Media & Learning',en:'VIDEHA MEDIA & LEARNING',title:'Documentary, teaching, poetry and accessibility.',text:'Open all 28 source-supplied links for Parallel History and Philosophy, classical-philosophy documentaries, drama, Water-Burial teaching resources, poetry, eLearning and Accessible Videha.',ids:[],href:'/gajendra-preeti/media-learning/en/',linkTitle:'VIDEHA MEDIA & LEARNING',linkMeta:'28 links · 4 curated paths · Maithili + English'},
  {id:'memory',label:'Archives and research',en:'For the archive explorer',title:'Open the pages of memory.',text:'Explore the Panji archive, literary history and critical writing about both authors.',ids:['p16','g6','j0']}
];

export function ReadingPaths(){return <Tabs defaultValue="children" className="reading-paths"><TabsList aria-label="Choose a reading path" className="path-tabs">{selections.map(s=><TabsTrigger key={s.id} value={s.id}>{s.label}</TabsTrigger>)}</TabsList>{selections.map(s=><TabsContent key={s.id} value={s.id} className="path-panel"><div><p className="eyebrow" lang="en">{s.en}</p><h3>{s.title}</h3><p>{s.text}</p></div><ol>{s.href?<li><span>01</span><a href={s.href}>{s.linkTitle}<small>{s.linkMeta} <b aria-hidden="true">→</b></small></a></li>:s.ids.map((id,i)=>{const w=works.find(w=>w.id===id)!;return <li key={id}><span>0{i+1}</span><a href={w.url}>{w.titleEn}<small>{w.nameEn} <b aria-hidden="true">↗</b></small></a></li>})}</ol></TabsContent>)}</Tabs>}

export function Catalogue(){return <CatalogueView english/>;}

export function ReadingProgress(){const[progress,setProgress]=useState(0);useEffect(()=>{let pending=false;const update=()=>{const max=document.documentElement.scrollHeight-window.innerHeight;setProgress(max>0?Math.min(100,window.scrollY/max*100):0);pending=false};const onScroll=()=>{if(!pending){pending=true;requestAnimationFrame(update)}};update();window.addEventListener('scroll',onScroll,{passive:true});window.addEventListener('resize',onScroll);return()=>{window.removeEventListener('scroll',onScroll);window.removeEventListener('resize',onScroll)}},[]);return <div className="reading-progress" aria-hidden="true" style={{transform:`scaleX(${progress/100})`}}/>}
