'use client';

import {useEffect,useState} from 'react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
import works from './works.json';

const selections=[
  {id:'children',label:'Children’s books',en:'For the curious reader',title:'Pictures, stories, imagination.',text:'Enter children’s literature through Preeti Thakur’s picture stories and translations.',ids:['p0','p1','p13']},
  {id:'literature',label:'Fiction and poetry',en:'For the literary explorer',title:'From short fiction to the novel.',text:'Three starting points in Gajendra Thakur’s fiction and poetry.',ids:['g0','g2','g4']},
  {id:'memory',label:'Archives and research',en:'For the archive explorer',title:'Open the pages of memory.',text:'Explore the Panji archive, literary history and the writers’ joint criticism.',ids:['p16','g6','j0']}
];

export function ReadingPaths(){return <Tabs defaultValue="children" className="reading-paths"><TabsList aria-label="Choose a reading path" className="path-tabs">{selections.map(s=><TabsTrigger key={s.id} value={s.id}>{s.label}</TabsTrigger>)}</TabsList>{selections.map(s=><TabsContent key={s.id} value={s.id} className="path-panel"><div><p className="eyebrow" lang="en">{s.en}</p><h3>{s.title}</h3><p>{s.text}</p></div><ol>{s.ids.map((id,i)=>{const w=works.find(w=>w.id===id)!;return <li key={id}><span>0{i+1}</span><a href={w.url}>{w.titleEn}<small>{w.nameEn} <b aria-hidden="true">↗</b></small></a></li>})}</ol></TabsContent>)}</Tabs>}

export function Catalogue(){const[query,setQuery]=useState('');const[author,setAuthor]=useState('all');const[expanded,setExpanded]=useState(false);
const normalized=query.normalize('NFC').toLocaleLowerCase().replace(/[०-९]/g,d=>String('०१२३४५६७८९'.indexOf(d))).trim();
const filtered=works.filter(w=>(author==='all'||w.author===author)&&[w.title,w.name,w.titleEn,w.nameEn,w.kindEn,w.year,w.keywords,w.noteEn].join(' ').normalize('NFC').toLocaleLowerCase().includes(normalized));
const visible=expanded?filtered:filtered.slice(0,6);
return <div className="catalogue"><div className="catalogue-tools"><label htmlFor="work-search">Find a book <span lang="en">/ Search the selection</span><Input id="work-search" type="search" value={query} onChange={e=>{setQuery(e.target.value);setExpanded(false)}} placeholder="Title, author, year…"/></label><div className="author-filters" role="group" aria-label="Filter by author">{[['all','All'],['preeti','Preeti'],['gajendra','Gajendra'],['joint','Joint']].map(([value,label])=><Button key={value} variant="ghost" aria-pressed={author===value} onClick={()=>{setAuthor(value);setExpanded(false)}}>{label}</Button>)}</div></div><div className="results-line"><span role="status" aria-live="polite">{filtered.length} works · {visible.length} shown</span><span lang="en">SELECTED WORKS / {works.length}</span></div><div className="work-grid">{visible.map((w)=><article className={'work-card '+w.author} key={w.id}><div className="work-top"><span>{w.kindEn}</span><span>{w.year||'—'}</span></div><div><p className="work-author">{w.nameEn}</p><h3><a href={w.url}>{w.titleEn}<span className="work-arrow" aria-hidden="true">↗</span></a></h3></div><div className="work-bottom"><p>{w.noteEn||'Videha catalogue'}</p><a href={w.source} aria-label={w.titleEn+' — source'}>Source ↗</a></div></article>)}</div>{filtered.length===0&&<div className="no-results"><h3>No works found.</h3><p>Try another title, author or year.</p><Button onClick={()=>{setQuery('');setAuthor('all')}}>Clear search</Button></div>}{filtered.length>6&&<Button className="show-more" variant="outline" onClick={()=>setExpanded(!expanded)}>{expanded?'Show fewer ↑':`Show ${filtered.length-6} more works ↓`}</Button>}<p className="catalogue-note">This is a selection. For the complete catalogue, visit <a href="https://www.videha.co.in/pothi.htm">Videha Books ↗</a> . Years refer to editions; an em dash means no year is recorded here.</p><noscript><p>Full bibliography at <a href="https://www.videha.co.in/pothi.htm">Videha Books</a> पर पढ़ू।</p></noscript></div>}

export function ReadingProgress(){const[progress,setProgress]=useState(0);useEffect(()=>{let pending=false;const update=()=>{const max=document.documentElement.scrollHeight-window.innerHeight;setProgress(max>0?Math.min(100,window.scrollY/max*100):0);pending=false};const onScroll=()=>{if(!pending){pending=true;requestAnimationFrame(update)}};update();window.addEventListener('scroll',onScroll,{passive:true});window.addEventListener('resize',onScroll);return()=>{window.removeEventListener('scroll',onScroll);window.removeEventListener('resize',onScroll)}},[]);return <div className="reading-progress" aria-hidden="true" style={{transform:`scaleX(${progress/100})`}}/>}
