import StructuredData from './structured-data';
import {Catalogue,ReadingPaths,ReadingProgress} from './atlas';
import works from './works.json';
import {CriticismTeaser} from './criticism-teaser';
export const dynamic = 'force-static';
const timeline=[
 {year:'2002',name:'प्रीति',title:'छोट आ पैघ',text:'बाल चित्रकथाक मैथिली अनुवादक प्रथम संस्करण। 2022 मे संशोधित संस्करण।',source:'https://www.videha.co.in/kids.htm'},
 {year:'2004',name:'विदेहक यात्रा',title:'भालसरिक गाछ',text:'5 जुलाई: गजेन्द्र ठाकुरक ब्लॉगक आरम्भ — विदेहक डिजिटल यात्राक एक पड़ाव।',source:'https://gajendrathakur.blogspot.com/2026/08/blog-post.html'},
 {year:'2007',name:'प्रीति',title:'पञ्जी-अभिलेख',text:'मूल मिथिलाक्षर ताड़पत्रक संकलन, स्कैनिंग आ सूचीकरण।',source:'https://www.videha.co.in/pothi.htm'},
 {year:'2008',name:'प्रीति / विदेह',title:'चित्रकथा आ ई-पत्रिका',text:'गोनू झा आ आन मैथिली चित्रकथा। एही वर्ष 1 जनवरीसँ “विदेह” नामेँ पाक्षिक ई-पत्रिकाक यात्रा।',source:'https://gajendrathakur.blogspot.com/2026/08/blog-post.html'},
 {year:'2009',name:'गजेन्द्र / प्रीति',title:'रचनाक अनेक रूप',text:'गल्प-गुच्छ, संकर्षण, सहस्रबाढ़नि; प्रीति ठाकुरक मैथिली चित्रकथा।',source:'https://www.videha.co.in/pothi.htm'},
 {year:'2012',name:'प्रीति',title:'विद्यापतिक पुरुष परीक्षा',text:'बाल साहित्यक रूपमे प्रकाशित कृति।',source:'https://www.videha.co.in/kids.htm'},
 {year:'2024',name:'प्रीति / गजेन्द्र',title:'नव पाठ, नव रूप',text:'हमर मोनक इच्छा — प्रीति ठाकुरक अनुवाद। सहस्रबाढ़नि — गजेन्द्र ठाकुरक ग्राफिक उपन्यास संस्करण।',source:'https://www.videha.co.in/pothi.htm'},
 {year:'2026',name:'विदेह',title:'समग्रसँ आगाँ',text:'रचना, भाषा-संसाधन, श्रव्य संस्करण आ शोध-परियोजनाक संग गजेन्द्र ठाकुर समग्रक डिजिटल प्रवेश-द्वार।',source:'https://gajendrathakur.blogspot.com/2026/08/blog-post.html'}
];
export default function Home(){return <>
<ReadingProgress/>
<a className="skip" href="#main">मुख्य सामग्रीपर जाउ</a>
<header className="masthead"><a className="brand" href="#top">प्रीति <span>×</span> गजेन्द्र<small lang="en">THE VIDEHA LITERARY ATLAS</small></a><nav aria-label="मुख्य नेविगेशन"><a href="/gajendra-preeti/en/" lang="en" className="language-link">English</a><a href="/gajendra-preeti/criticism/">समालोचना<small lang="en">Criticism</small></a><a href="#writers">परिचय<small lang="en">Writers</small></a><a href="#archive">रचना संसार<small lang="en">Works</small></a><a href="#journey">समय-यात्रा<small lang="en">Timeline</small></a><a href="https://www.videha.co.in/">विदेह ↗</a></nav></header>
<main id="main"><StructuredData/>
<section className="hero" id="top" aria-labelledby="site-title"><div className="eyebrow"><span>मैथिली · साहित्य · स्मृति</span><span lang="en">VIDEHA / LITERARY ATLAS</span></div><p className="verified-banner">स्रोत-जाँच: 8 सितम्बर 2026 · <a href="#sources">स्रोत आ पद्धति ↓</a></p><p className="hero-kicker">दू रचनाकार। साझा साहित्यिक संसार।</p><h1 id="site-title"><span>प्रीति ठाकुर</span><i>आ</i><span>गजेन्द्र ठाकुर</span></h1><div className="hero-bottom"><p>चित्रकथासँ पञ्जी धरि।<br/>सृजनसँ डिजिटल अभिलेख धरि।</p><a className="round-link" href="#paths"><span>पढ़बाक बाट चुनू</span><b aria-hidden="true">↓</b></a><p className="english" lang="en">Two bodies of work.<br/>A language in common.</p></div><nav className="index-strip" aria-label="पन्नाक अनुक्रम"><a href="#writers">01 / रचनाकार</a><a href="#archive">02 / रचना संसार</a><a href="#journey">03 / समय-यात्रा</a><a href="#videha">04 / विदेह</a></nav></section>

<section id="writers" className="section"><div className="section-heading"><p className="eyebrow" lang="en">01 / THE WRITERS</p><h2>अपन-अपन स्वर।<br/><em>एक भाषा।</em></h2></div><div className="writers"><article id="preeti"><div className="writer-intro"><span className="number">01 / PREETI THAKUR</span><figure className="portrait preeti-photo"><img src="/gajendra-preeti/images/preeti-thakur.jpg" alt="प्रीति ठाकुर — विदेह अभिलेखक फोटो" width="200" height="112" loading="lazy"/><figcaption><a href="https://www.videha.co.in/ratna.htm">विदेह / मिथिला रत्न ↗</a></figcaption></figure></div><h3>प्रीति ठाकुर</h3><p className="writer-role">बाल साहित्य · अनुवाद · पाण्डुलिपि संरक्षण</p><p>मैथिली चित्रकथा आ बाल-पोथीक अनुवाद हुनक रचना संसारक प्रमुख धारा अछि। विदेहक सूचीमे पञ्जी ताड़पत्रक संकलन, स्कैनिंग आ सूचीकरण सेहो हुनक नामसँ दर्ज अछि।</p><dl><div><dt>मूल कृति</dt><dd>गोनू झा आ आन मैथिली चित्रकथा</dd></div><div><dt>अनुवाद</dt><dd>छोट आ पैघ · हमर मोनक इच्छा</dd></div><div><dt>अभिलेख</dt><dd>मूल मिथिलाक्षर ताड़पत्र पञ्जी</dd></div></dl><a className="text-link" href="https://www.videha.co.in/kids.htm">बाल-पोथी पढ़ू <span aria-hidden="true">↗</span></a></article><article id="gajendra"><div className="writer-intro"><span className="number">02 / GAJENDRA THAKUR</span><figure className="portrait"><img src="/gajendra-preeti/images/gajendra-thakur.jpg" alt="गजेन्द्र ठाकुर — उमेशबर्माक 2009 केर फोटो" width="264" height="339" loading="lazy"/><figcaption><a href="https://commons.wikimedia.org/wiki/File:GajendraThakur.jpg">Umeshberma · CC BY 3.0 ↗</a></figcaption></figure></div><h3>गजेन्द्र ठाकुर</h3><p className="writer-role">लेखन · शोध · सम्पादन</p><p>कथा, उपन्यास, कविता, नाटक आ समालोचनाक संग भाषा, लिपि आ साहित्यक इतिहासपर काज। विदेहक सम्पादकक रूपमे हुनक डिजिटल प्रकाशन आ अभिलेखक यात्रा सेहो जारी अछि।</p><dl><div><dt>सृजन</dt><dd>गल्प-गुच्छ · संकर्षण · सहस्रबाढ़नि</dd></div><div><dt>शोध</dt><dd lang="en">A Parallel History of Mithila & Maithili Literature</dd></div><div><dt>सम्पादन</dt><dd>विदेह — मैथिली पाक्षिक ई-पत्रिका</dd></div></dl><a className="text-link" href="https://www.videha.co.in/gajendra-thakur-samagra.htm">समग्र खोलू <span aria-hidden="true">↗</span></a></article></div><p className="source-note">परिचयक स्रोत: <a href="https://www.videha.co.in/pothi.htm">विदेह पोथी</a> · <a href="https://www.videha.co.in/gajendra-thakur-samagra.htm">गजेन्द्र ठाकुर समग्र</a></p></section>

<section id="paths" className="section paper"><div className="section-heading"><p className="eyebrow" lang="en">A READER'S COMPASS</p><h2>कतयसँ शुरू करी?</h2></div><ReadingPaths/></section>

<section id="archive" className="section archive"><div className="section-heading"><div><p className="eyebrow" lang="en">02 / SELECTED WORKS</p><span className="archive-count" aria-hidden="true">{works.length}</span></div><div><h2>रचना संसार</h2><p className="section-deck">पोथी, अनुवाद आ अभिलेख। शीर्षकपर क्लिक कऽ मूल संसाधन पढ़ू।</p></div></div><Catalogue/></section>

<section className="preservation section" aria-labelledby="preservation-title"><div><p className="eyebrow" lang="en">THE WORK OF PRESERVATION</p><h2 id="preservation-title">अक्षर बाँचल रहय।<br/>पाठक धरि पहुँचय।</h2><p>प्रीति ठाकुरक पञ्जी-संकलन आ गजेन्द्र ठाकुरक ब्रेल संस्करण — संरक्षण आ पाठकक पहुँच, एहि साहित्यिक संसारक दू धारा।</p></div><div className="preservation-facts"><article><span className="fact-number">11,000</span><h3>मूल मिथिलाक्षर ताड़पत्र</h3><p>विदेहक सूची अनुसार प्रीति ठाकुर द्वारा संकलित, स्कैन आ सूचीबद्ध। खण्ड I–XXII · 2007।</p><a href="https://drive.google.com/file/d/13tKREg6BqXkfk3n1jGfrgnQVx-Y5hQMs/view?usp=sharing">पञ्जी-अभिलेख खोलू ↗</a></article><article><span className="braille" aria-hidden="true">⠃⠗⠑⠇</span><h3>सहस्रबाढ़नि — ब्रेल मैथिली</h3><p>2009 केर ब्रेल संस्करणक लिंक गजेन्द्र ठाकुर समग्रमे उपलब्ध अछि।</p><a href="https://www.videha.co.in/gajendra-thakur-samagra.htm#braille">ब्रेल संसाधन खोलू ↗</a></article></div></section>

<section id="journey" className="section journey"><div className="section-heading"><p className="eyebrow" lang="en">03 / A LITERARY CHRONOLOGY</p><div><h2>समयक पन्नापर।</h2><p className="section-deck">प्रकाशन आ अभिलेखक चुनल पड़ाव।</p></div></div><p className="timeline-note">ई चुनल, स्रोतसँ पुष्ट पड़ावक सूची अछि; प्रत्येक वर्षक गतिविधिक विवरण नहि। वर्षक अन्तरालक अर्थ लेखन वा प्रकाशन रुकब नहि अछि।</p><ol className="timeline">{timeline.map(t=><li key={t.year} id={"timeline-"+t.year} data-citation-title={t.year+" — "+t.title}><div className="timeline-year">{t.year}</div><div><span className="timeline-name">{t.name}</span><h3><a href={"#timeline-"+t.year}>{t.title}</a></h3><p>{t.text}</p><a href={t.source}>स्रोत देखू ↗</a>{t.year==='2008'&&<a className="extra-source" href="https://www.videha.co.in/kids.htm">चित्रकथा सूची ↗</a>}</div></li>)}</ol></section>

<section id="videha" className="section paper ecosystem"><div className="section-heading"><p className="eyebrow" lang="en">04 / BEYOND THIS PAGE</p><h2>विदेहक संसारमे।</h2></div><div className="ecosystem-grid"><a href="https://www.videha.co.in/"><span>01 / JOURNAL</span><h3>नूतन अंक</h3><p>मैथिली गद्य, पद्य आ सम्पादकीय।</p><b aria-hidden="true">↗</b></a><a href="https://www.videha.co.in/pothi.htm"><span>02 / LIBRARY</span><h3>विदेह पोथी</h3><p>लेखक, विधा आ कृतिक विस्तृत पुस्तक सूची।</p><b aria-hidden="true">↗</b></a><a href="https://www.videha.co.in/kids.htm"><span>03 / YOUNG READERS</span><h3>शिशु उत्सव</h3><p>बाल-पोथी आ सीखबाक संसाधन।</p><b aria-hidden="true">↗</b></a><a href="https://www.videha.co.in/gajendra-thakur-samagra.htm"><span>04 / COLLECTED WORKS</span><h3>गजेन्द्र समग्र</h3><p>मौलिक रचना, अनुवाद, श्रव्य संस्करण आ शोध।</p><b aria-hidden="true">↗</b></a></div></section>

<CriticismTeaser lang="mai"/><section id="sources" className="section sources"><div className="section-heading"><p className="eyebrow" lang="en">EDITORIAL NOTES</p><h2>स्रोतसँ जुड़ल।</h2></div><div className="source-columns"><div><p>एहि पन्नाक कृति-सूची आ समय-यात्रा विदेहक सार्वजनिक अभिलेखपर आधारित अछि। रचनाक पूर्ण पाठ मूल प्रकाशनपर पढ़ू।</p><p>स्रोत-जाँच: 8 सितम्बर 2026। ई चयन पूर्ण ग्रन्थसूची नहि अछि। रचना आ चित्रक अधिकार सम्बन्धित रचनाकार आ अधिकारधारीक लग सुरक्षित अछि।</p></div><div><details><summary>कृति आ समय-यात्राक स्रोत</summary><ul><li><a href="https://www.videha.co.in/pothi.htm">विदेह पोथी — कृति, वर्ष आ पञ्जी</a></li><li><a href="https://www.videha.co.in/kids.htm">शिशु उत्सव — मूल आ अनूदित बाल साहित्य</a></li><li><a href="https://www.videha.co.in/gajendra-thakur-samagra.htm">गजेन्द्र ठाकुर समग्र — साहित्य, भाषा आ शोध</a></li><li><a href="https://gajendrathakur.blogspot.com/2026/08/blog-post.html">भालसरिक गाछ — विदेहक डिजिटल यात्रा</a></li><li><a href="https://books.google.com/books?id=SvntEAAAQBAJ">विदेह अंक 386 — लेखक परिचय आ ब्रेल संस्करणक वर्ष</a></li></ul></details><details><summary>चित्रक स्रोत आ श्रेय</summary><p>प्रीति ठाकुर: <a href="https://www.videha.co.in/ratna.htm">विदेह मिथिला रत्न</a> · <a href="https://www.videha.co.in/prity.jpg">मूल फोटो</a>।</p><p lang="en">Gajendra Thakur: <a href="https://commons.wikimedia.org/wiki/File:GajendraThakur.jpg">Umeshberma, 2009, Wikimedia Commons</a>, <a href="https://creativecommons.org/licenses/by/3.0/">CC BY 3.0</a>. Displayed without modification.</p></details><details><summary>पढ़बाक सुविधा</summary><p>कीबोर्डसँ लिंक आ नियंत्रण चुनि सकैत छी। डिवाइसक reduced-motion विकल्पक सम्मान कएल जाइत अछि। मूल PDF आ बाहरी वेबसाइटक पठन-सुविधा अलग भऽ सकैत अछि।</p><p lang="en">Use browser zoom to enlarge text. Search accepts Maithili text, English author names and either Devanagari or Latin year numerals.</p></details></div></div></section>
</main><footer><div><a className="footer-title" href="#top">प्रीति <span>आ</span> गजेन्द्र</a><p lang="en">A VIDEHA LITERARY ATLAS · MAITHILI</p></div><div><a href="#sources">स्रोत आ श्रेय</a><a href="https://github.com/videha-ejournal/gajendra-preeti">GitHub ↗</a><a href="#top">ऊपर जाउ ↑</a></div></footer></>}
