import works from './works.json';
import preetiChildren from '../content/preeti-children-provenance.json';
import gajendraTranslations from '../content/gajendra-maithili-translations-provenance.json';
const base='https://videha-ejournal.github.io/gajendra-preeti/';
const bookKinds=new Set(['Children’s literature','Fiction','Drama','Poetry','Translation','Scripts']);
const preetiOriginalIds=new Set(preetiChildren.originalMaithili.map(w=>w.id));
const preetiTranslationIds=new Set(preetiChildren.englishToMaithiliTranslations.map(w=>w.id));
export default function StructuredData({english=false}:{english?:boolean}){
 const people=[{'@type':'Person','@id':base+'#preeti',name:'Preeti Thakur',alternateName:'प्रीति ठाकुर',url:base+'#preeti',image:base+'images/preeti-thakur.jpg',subjectOf:{'@type':'WebPage',url:'https://www.videha.co.in/ratna.htm'}},{'@type':'Person','@id':base+'#gajendra',name:'Gajendra Thakur',alternateName:'गजेन्द्र ठाकुर',url:base+'#gajendra',image:base+'images/gajendra-thakur.jpg',sameAs:['https://www.videha.co.in/gajendra-thakur-samagra.htm']}];
 const preeti={'@id':base+'#preeti'};
 const gajendra={'@id':base+'#gajendra'};
 const originalChildrenSeries={'@type':'CreativeWorkSeries','@id':base+'#gajendra-children-37-mai',name:'37 Maithili Children Graphic Novels by Gajendra Thakur',alternateName:'गजेन्द्र ठाकुरक ३७ मैथिली बाल-उपन्यास / ग्राफिक उपन्यास',author:gajendra,inLanguage:'mai',description:'A series of 37 original Maithili children’s novels / graphic novels written by Gajendra Thakur.',workTranslation:{'@id':base+'#gajendra-children-37-en'},additionalProperty:{'@type':'PropertyValue',name:'Series count',value:37}};
 const englishChildrenSeries={'@type':'CreativeWorkSeries','@id':base+'#gajendra-children-37-en',name:'37 Maithili Children Graphic Novels by Gajendra Thakur — English translations',author:gajendra,translator:gajendra,inLanguage:'en',description:'English translations by Gajendra Thakur of his 37 original Maithili children’s novels / graphic novels.',translationOfWork:{'@id':base+'#gajendra-children-37-mai'},additionalProperty:{'@type':'PropertyValue',name:'Series count',value:37}};
 const records=works.map(w=>{
  const person={'@id':base+'#'+w.author};
  const credit=w.author==='joint'?{about:people.map(p=>({'@id':p['@id']}))}:preetiTranslationIds.has(w.id)?{translator:preeti}:preetiOriginalIds.has(w.id)?{author:preeti}:w.id==='p16'?{contributor:{'@type':'Role',roleName:'Compilation, scanning and cataloguing',contributor:person}}:{author:person};
  const isBook=bookKinds.has(w.kindEn);
  const translation=preetiTranslationIds.has(w.id)?{inLanguage:'mai',translationOfWork:{'@type':'Book',name:w.titleEn,inLanguage:'en'}}:{};
  return {'@type':isBook?'Book':'CreativeWork','@id':base+'#work-'+w.id,name:w.title,alternateName:w.titleEn,url:base+(english?'en/':'')+'#work-'+w.id,genre:w.kindEn,...credit,...(w.year?{datePublished:String(w.year)}:{}),...translation,encoding:{'@type':'MediaObject',contentUrl:w.url},isBasedOn:{'@type':'WebPage',url:w.source}};
 });
 const preetiOriginalSeries={'@type':'CreativeWorkSeries','@id':base+'#preeti-children-original-4',name:'Four original Maithili children’s works by Preeti Thakur',alternateName:'प्रीति ठाकुरक चारि मूल मैथिली बाल-कृति',author:preeti,inLanguage:'mai',additionalProperty:{'@type':'PropertyValue',name:'Series count',value:4},hasPart:preetiChildren.originalMaithili.map(w=>({'@id':base+'#work-'+w.id}))};
 const preetiTranslationSeries={'@type':'CreativeWorkSeries','@id':base+'#preeti-children-translations-12',name:'Twelve English-to-Maithili picture-book translations by Preeti Thakur',alternateName:'प्रीति ठाकुरक बारह English-सँ-मैथिली बाल-चित्रपोथी अनुवाद',translator:preeti,inLanguage:'mai',additionalProperty:[{'@type':'PropertyValue',name:'Series count',value:12},{'@type':'PropertyValue',name:'Translation direction',value:'English → Maithili'}],hasPart:preetiChildren.englishToMaithiliTranslations.map(w=>({'@id':base+'#work-'+w.id}))};
 const gajendraTranslationCorpus={'@type':'ItemList','@id':base+'#gajendra-maithili-translations-45',name:'45 Maithili translation entries by Gajendra Thakur',numberOfItems:45,itemListElement:gajendraTranslations.items.map(item=>({'@type':'ListItem',position:item.number,item:{'@type':'CreativeWork',name:item.titleMai,inLanguage:'mai',translator:gajendra,encoding:{'@type':'MediaObject',contentUrl:item.url},additionalProperty:{'@type':'PropertyValue',name:'Translation route',value:item.route==='indian-via-english'?'Various Indian languages → English intermediary → Maithili':'English → Maithili'}}}))};
 const pageUrl=base+(english?'en/':'');
 const graph={'@context':'https://schema.org','@graph':[...people,...records,preetiOriginalSeries,preetiTranslationSeries,originalChildrenSeries,englishChildrenSeries,gajendraTranslationCorpus,{'@type':'CollectionPage','@id':pageUrl,url:pageUrl,name:english?'Preeti Thakur & Gajendra Thakur — Videha Literary Atlas':'प्रीति ठाकुर आ गजेन्द्र ठाकुर',inLanguage:english?'en':'mai',dateModified:'2026-09-10',about:[...people.map(p=>({'@id':p['@id']})),{'@id':preetiOriginalSeries['@id']},{'@id':preetiTranslationSeries['@id']},{'@id':originalChildrenSeries['@id']},{'@id':englishChildrenSeries['@id']},{'@id':gajendraTranslationCorpus['@id']}],mainEntity:{'@type':'ItemList',numberOfItems:records.length,itemListElement:records.map((r,i)=>({'@type':'ListItem',position:i+1,item:{'@id':r['@id']}}))}}]};
 return <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(graph).replace(/</g,'\\u003c')}}/>;
}
